language: go
sudo: false
go:
  - 1.6
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
script:
  - go test -v ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - $HOME/gopath/bin/golint ./...
